title: FHU Help Pages
description: Git backed Wiki and resources for FHU

# social links
twitter_username: fh_unleashed # DO NOT include the @ character, or else the build will fail!
github_username:  fhunleashed # DO NOT include the @ character, or else the build will fail!

show_downloads: false # set to false to remove excerpts on the homepage
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme