title: FHU Help Pages
description: Git backed Wiki and resources for FHU

# social links
twitter_username: fh_unleashed # DO NOT include the @ character, or else the build will fail!
github_username:  fhunleashed # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 